from fastapi import APIRouter, HTTPException
from myapi.login import validate_token

router = APIRouter()
@router.post('/user')
def create_user(user:dict):
    # Logic to create a new user
    user_id = user.get("id")
    token= user.get("token")
  # This would be generated by the database
    if not user_id:
        return {"success": False, "message": "User ID is required"}
    elif not token:
        return {"success": False, "message": "Token is required"}
    # Validate the token before creating the user
    else:
        result = validate_token(user.get("token"))
        if result is False:
            return {"success": False, "message": "Invalid token"}
        else:
            # Here you would add the user to the database
            return {"success": True, "message": "User created successfully"}
